// Generated by CoffeeScript 1.3.3
(function() {
  var App, EventDispatcher, RCat, RCatList, RCatListView, RCatView, RLink, RLinkList, RTopicGroup, RTopicGroupList, RTopicGroupView, RedditEngine, VGroupEditor, VManageGroups, app, collectionToJson, reng, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  root = window;

  window.log = function() {
    if (this.console) {
      console.log(Array.prototype.slice.call(arguments));
    }
  };

  window.logj = function(prefix, arg) {
    return log("Obj: " + prefix);
  };

  App = (function() {

    function App() {}

    App.prototype.start = function() {
      var createDefaultGroups, ge, mg, mv, reng, tg,
        _this = this;
      log("Starting app at ");
      log(Date());
      this.topicGroups = new RTopicGroupList;
      log(21);
      createDefaultGroups = function() {
        _this.tgview.addTg("Casual", ["frontpage", "pics", "fffffffuuuuuuuuuuuu", "funny", "AdviceAnimals"]);
        return _this.tgview.addTg("Code", ["programming", "webdev", "javascript", "web_design", "html5", "coffeescript", "python"]);
      };
      $("#btnWizardCreate").on("click", function() {
        return createDefaultGroups();
      });
      $("#pagepreview").on("click", function() {
        $.mobile.changePage("#pagemain");
        return $("#previewIframe").attr("src", "");
      });
      this.shownCategories = new RCatList;
      log(38);
      root.redditengine = reng = new RedditEngine();
      this.tgview = tg = new RTopicGroupView;
      this.mainview = mv = new RCatListView;
      this.vManageGroups = mg = new VManageGroups;
      mg.render();
      this.vGroupEditor = ge = new VGroupEditor;
      log(53);
      EventDispatcher.bind("selectCategories", function(ev, cats) {
        log("setting categories", cats);
        mv.setCategories(cats);
        mv.render();
        return reng.fetchAll();
      });
      reng.initialize();
      createDefaultGroups();
      this.tgview.render();
      reng.fetchAll();
      return log("Started up");
    };

    return App;

  })();

  EventDispatcher = $({});

  app = new App();

  root.redditapp = app;

  collectionToJson = function(coll) {
    return coll.map(function(m) {
      var o;
      o = m.toJSON();
      o.cid = m.cid;
      return o;
    });
  };

  RLink = (function(_super) {

    __extends(RLink, _super);

    function RLink() {
      return RLink.__super__.constructor.apply(this, arguments);
    }

    RLink.prototype.defaults = {
      linkdesc: "no description"
    };

    return RLink;

  })(Backbone.Model);

  RCat = (function(_super) {

    __extends(RCat, _super);

    function RCat() {
      return RCat.__super__.constructor.apply(this, arguments);
    }

    RCat.prototype.defaults = {
      name: "funny"
    };

    return RCat;

  })(Backbone.Model);

  RTopicGroup = (function(_super) {

    __extends(RTopicGroup, _super);

    function RTopicGroup() {
      return RTopicGroup.__super__.constructor.apply(this, arguments);
    }

    RTopicGroup.prototype.defaults = {
      groupName: "mygroup",
      topics: ["pics", "funny"]
    };

    return RTopicGroup;

  })(Backbone.Model);

  RTopicGroupList = (function(_super) {

    __extends(RTopicGroupList, _super);

    function RTopicGroupList() {
      return RTopicGroupList.__super__.constructor.apply(this, arguments);
    }

    RTopicGroupList.prototype.model = RTopicGroup;

    return RTopicGroupList;

  })(Backbone.Collection);

  RTopicGroupView = (function(_super) {

    __extends(RTopicGroupView, _super);

    function RTopicGroupView() {
      return RTopicGroupView.__super__.constructor.apply(this, arguments);
    }

    RTopicGroupView.prototype.el = "#topic-group-area";

    RTopicGroupView.prototype.initialize = function() {
      var pat,
        _this = this;
      pat = $("#topic-group-template").html();
      log("Using template", pat);
      this.template = Handlebars.compile(pat);
      this.tglist = app.topicGroups;
      return this.tglist.bind("change remove", function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return _this.render();
      });
    };

    RTopicGroupView.prototype.bindEvents = function() {
      var _this = this;
      $(".tg-name").on("click", function(ev) {
        return _this.doSelectGroup(ev);
      });
      return $(".tg-topic").on("click", function(ev) {
        return _this.doSelectTopic(ev);
      });
    };

    RTopicGroupView.prototype.render = function() {
      var _this = this;
      this.$el.empty();
      this.tglist.each(function(m) {
        var rend;
        log("obj for rend", m.toJSON());
        rend = _this.template({
          tgname: m.get("groupName"),
          topics: m.get("topics"),
          tgid: m.cid
        });
        _this.$el.append(rend);
        return log("Rendered", rend);
      });
      return this.bindEvents();
    };

    RTopicGroupView.prototype.addTg = function(name, topics) {
      var m;
      m = new RTopicGroup({
        groupName: name,
        topics: topics
      });
      return this.tglist.add(m);
    };

    RTopicGroupView.prototype.makeCurrent = function(elem) {
      $(".tg-current-choice").removeClass("tg-current-choice");
      return elem.addClass("tg-current-choice");
    };

    RTopicGroupView.prototype.doSelectGroup = function(ev) {
      var cid, m, trg;
      trg = $(ev.target);
      cid = trg.data("cid");
      this.makeCurrent(trg);
      m = this.tglist.getByCid(cid);
      return EventDispatcher.trigger("selectCategories", [m.get("topics")]);
    };

    RTopicGroupView.prototype.doSelectTopic = function(ev) {
      var topic, trg;
      log("Topic selected");
      trg = $(ev.target);
      this.makeCurrent(trg);
      topic = trg.text();
      return EventDispatcher.trigger("selectCategories", [[topic]]);
    };

    RTopicGroupView.prototype.events = {
      "click .tg-name": "doSelectGroup",
      "click .tg-topic": "doSelectTopic"
    };

    return RTopicGroupView;

  })(Backbone.View);

  RLinkList = (function(_super) {

    __extends(RLinkList, _super);

    function RLinkList() {
      return RLinkList.__super__.constructor.apply(this, arguments);
    }

    RLinkList.prototype.model = RLink;

    return RLinkList;

  })(Backbone.Collection);

  RCatList = (function(_super) {

    __extends(RCatList, _super);

    function RCatList() {
      return RCatList.__super__.constructor.apply(this, arguments);
    }

    RCatList.prototype.model = RCat;

    return RCatList;

  })(Backbone.Collection);

  RCatListView = (function(_super) {

    __extends(RCatListView, _super);

    function RCatListView() {
      return RCatListView.__super__.constructor.apply(this, arguments);
    }

    RCatListView.prototype.el = "#catlist-container";

    RCatListView.prototype.initialize = function() {
      var pat;
      log(192);
      _.bindAll(this);
      this.categories_coll = new RCatList;
      pat = $("#catlist-template").html();
      this.catlisttmpl = Handlebars.compile(pat);
      return this.singlecatviews = {};
    };

    RCatListView.prototype.render = function() {
      var all,
        _this = this;
      log(201);
      this.$el.empty();
      log(204);
      all = $("<div>");
      log(206);
      app.shownCategories.each(function(m) {
        var appended, name, nv, r, rendered;
        log(208);
        name = m.get("name");
        log(name);
        rendered = _this.catlisttmpl({
          catname: name
        });
        log(rendered);
        appended = $(rendered).appendTo(all);
        r = appended.find(".catlist-links");
        nv = new RCatView({
          el: r
        });
        return _this.singlecatviews[name] = nv;
      });
      log(224);
      return this.$el.append(all);
    };

    RCatListView.prototype.setCategories = function(cats) {
      var name;
      log(224);
      app.shownCategories.reset((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = cats.length; _i < _len; _i++) {
          name = cats[_i];
          _results.push({
            name: name
          });
        }
        return _results;
      })());
      return log(226);
    };

    RCatListView.prototype.getView = function(name) {
      return this.singlecatviews[name];
    };

    RCatListView.prototype.categories = function() {
      return this.categories_coll;
    };

    return RCatListView;

  })(Backbone.View);

  RCatView = (function(_super) {

    __extends(RCatView, _super);

    function RCatView() {
      return RCatView.__super__.constructor.apply(this, arguments);
    }

    RCatView.prototype.events = {
      "click .linkcontainer": "doSelect",
      "click .rightedge": "doSelectComments"
    };

    RCatView.prototype.modelByCid = function(cid) {
      return this.coll.getByCid(cid);
    };

    RCatView.prototype.openWindow = function(url) {
      console.log("Open url", url);
      return window.open(url);
    };

    RCatView.prototype.doSelect = function(ev) {
      var cid, m, url;
      cid = $(ev.currentTarget).data("cid");
      m = this.modelByCid(cid);
      url = m.get("url");
      return this.openWindow(url);
    };

    RCatView.prototype.doSelectComments = function(ev) {
      var cid, fullurl, m, plink;
      cid = $(ev.currentTarget).closest(".linkcontainer").data("cid");
      m = this.modelByCid(cid);
      plink = m.get("permalink");
      fullurl = "http://reddit.com" + plink + ".compact";
      ev.stopPropagation();
      return this.openWindow(fullurl);
    };

    RCatView.prototype.initialize = function() {
      var pat;
      this.coll = new RLinkList;
      _.bindAll(this);
      pat = $("#link-template").html();
      return this.linktmpl = Handlebars.compile(pat);
    };

    RCatView.prototype.renderOne = function(m) {
      var commentsurl, expanded, plink, sc, score, thumb;
      thumb = m.get("thumbnail");
      if (thumb === "default" || thumb === "self") {
        thumb = "";
      }
      sc = m.get("score");
      if (sc >= 0) {
        score = "+" + sc;
      } else {
        score = "-" + sc;
      }
      plink = m.get("permalink");
      commentsurl = "http://reddit.com" + plink + ".compact";
      expanded = this.linktmpl({
        linkdesc: m.get("title"),
        linkscore: score,
        linkimg: thumb,
        linkcomments: m.get("num_comments"),
        commentsurl: commentsurl,
        url: m.get("url"),
        cid: m.cid
      });
      return expanded;
    };

    RCatView.prototype.render = function() {
      var all,
        _this = this;
      all = $('<ul data-role="listview" data-theme="c">');
      this.coll.each(function(m) {
        return all.append($(_this.renderOne(m)));
      });
      this.$el.empty();
      this.$el.append(all);
      return this.$el.trigger("create");
    };

    RCatView.prototype.mkModel = function(d) {
      var m;
      m = new RLink;
      m.set(d);
      return m;
    };

    RCatView.prototype.addLink = function(d) {
      var m;
      m = this.mkModel(d);
      return this.coll.add(m);
    };

    return RCatView;

  })(Backbone.View);

  VManageGroups = (function(_super) {

    __extends(VManageGroups, _super);

    function VManageGroups() {
      return VManageGroups.__super__.constructor.apply(this, arguments);
    }

    VManageGroups.prototype.el = "#manage-groups-area";

    VManageGroups.prototype.events = {
      "click .topic-group-item": "doSelectGroup",
      "click #btnNewGroup": "doNewGroup"
    };

    VManageGroups.prototype.initialize = function() {
      var pat,
        _this = this;
      _.bindAll(this);
      pat = $("#manage-groups-template").text();
      this.tmplManageGroups = Handlebars.compile(pat);
      return app.topicGroups.bind("change remove", function() {
        return _this.render();
      });
    };

    VManageGroups.prototype.render = function() {
      var context, h;
      context = {
        groups: collectionToJson(app.topicGroups)
      };
      h = this.tmplManageGroups(context);
      this.$el.html(h);
      return this.$el.trigger("create");
    };

    VManageGroups.prototype.modelByCid = function(cid) {
      return app.topicGroups.getByCid(cid);
    };

    VManageGroups.prototype.doSelectGroup = function(ev) {
      var m;
      m = this.modelByCid($(ev.currentTarget).data("cid"));
      return this.switchToGroupEditor(m);
    };

    VManageGroups.prototype.switchToGroupEditor = function(m) {
      app.vGroupEditor.setModel(m);
      return $.mobile.changePage("#pagegroupeditor");
    };

    VManageGroups.prototype.doNewGroup = function(ev) {
      var m;
      m = app.topicGroups.create({
        groupName: "<untitled>",
        topics: []
      });
      this.switchToGroupEditor(m);
      return app.vGroupEditor.setModel(m);
    };

    return VManageGroups;

  })(Backbone.View);

  VGroupEditor = (function(_super) {

    __extends(VGroupEditor, _super);

    function VGroupEditor() {
      return VGroupEditor.__super__.constructor.apply(this, arguments);
    }

    VGroupEditor.prototype.el = "#group-editor-area";

    VGroupEditor.prototype.events = {
      "click #btnAdd": "doAddCat",
      "click .aRemoveCat": "doRemoveCat",
      "click #btnApplyChangeGroupName": "doChangeGroupName",
      "keyup #inpGroupName": "doCheckGroupName"
    };

    VGroupEditor.prototype.initialize = function() {
      var pat,
        _this = this;
      _.bindAll(this);
      pat = $("#group-editor-template").text();
      this.tmpl = Handlebars.compile(pat);
      return $("#btnDeleteGroup").on("click", function() {
        _this.model.destroy();
        return history.back();
      });
    };

    VGroupEditor.prototype.doCheckGroupName = function() {
      var b, kl, ref, t;
      b = $("#btnApplyChangeGroupName");
      t = $("#inpGroupName").val();
      kl = 'ui-disabled';
      ref = false;
      if (t !== this.model.get("groupName")) {
        if (b.hasClass(kl)) {
          b.removeClass("ui-disabled");
          return ref = true;
        }
      } else {
        if (!b.hasClass(kl)) {
          b.addClass("ui-disabled");
          return ref = true;
        }
      }
    };

    VGroupEditor.prototype.updateList = function() {
      var ul;
      ul = this.$(".rootlist");
      ul.listview();
      return ul.listview("refresh");
    };

    VGroupEditor.prototype.render = function() {
      var context, h;
      if (!this.model) {
        return;
      }
      context = this.model.toJSON();
      h = this.tmpl(context);
      this.$el.html(h);
      return this.$el.trigger("create");
    };

    VGroupEditor.prototype.setModel = function(m) {
      var _this = this;
      this.model = m;
      this.render();
      m.on("change", function() {
        return _this.render();
      });
      return this.doCheckGroupName();
    };

    VGroupEditor.prototype.doAddCat = function(ev) {
      var m, t, topics;
      t = $("#inpNewCategory").val();
      if (t.length < 1) {
        return;
      }
      m = this.model;
      topics = m.get("topics");
      return m.set("topics", topics.concat([t]));
    };

    VGroupEditor.prototype.doRemoveCat = function(ev) {
      var elem, m, toRemove, topics, ul;
      elem = $(ev.currentTarget);
      toRemove = elem.text();
      ul = this.$(".rootlist");
      m = this.model;
      topics = _.without(m.get("topics"), toRemove);
      return m.set("topics", topics);
    };

    VGroupEditor.prototype.doChangeGroupName = function(ev) {
      var t;
      t = $("#inpGroupName").val();
      this.model.set("groupName", t);
      return this.doCheckGroupName();
    };

    return VGroupEditor;

  })(Backbone.View);

  RedditEngine = (function() {

    function RedditEngine() {}

    RedditEngine.prototype.initialize = function() {
      this.cats = [];
      return this.linkviews = {};
    };

    RedditEngine.prototype.fetchAll = function() {
      var _this = this;
      log(506);
      return app.shownCategories.each(function(m) {
        return _this.fetchLinks(m.get("name", ""));
      });
    };

    RedditEngine.prototype.fetchLinks = function(cat, qargs) {
      var catfrag, lv, url,
        _this = this;
      log(511);
      qargs = "jsonp=?&";
      if (cat === "frontpage") {
        catfrag = "";
      } else {
        catfrag = "/r/" + cat + "/";
      }
      url = "http://www.reddit.com" + catfrag + "/.json?" + qargs + " ";
      lv = app.mainview.getView(cat);
      return $.ajax({
        url: url,
        jsonp: "jsonp",
        dataType: "jsonp",
        success: function(resp) {
          var d, it, items, _i, _len;
          items = resp.data.children;
          for (_i = 0, _len = items.length; _i < _len; _i++) {
            it = items[_i];
            d = it.data;
            lv.addLink(d);
          }
          return lv.render();
        }
      });
    };

    return RedditEngine;

  })();

  root.RedditEngine = RedditEngine;

  reng = null;

  $(function() {
    log("starting up");
    log("...still...");
    app.start();
    return log("post start up");
  });

}).call(this);
